### ISSUE TITLE
tv_grab_dvb

### ISSUE THREAD

**Issue by grkblood13** [kanehekili/MicroDVBRecorder#2]
Could you please make the tv_grab_dvb source available with the changes you had to make to get it to run on ARM? Also, some build instructions for the project would be nice. I didn't see any in the readme. Thanks!

**Comment by kanehekili** [comment]
I'll upload the source code. Are you aware, that there is a "arm" binary (that runs on cubieboard and Raspi currently) ?
If running on arm, the binary has to be copied directly into the "bin" folder (not a good solution, you may rename the existing binary into tv_grab_X86)
As mentioned in the readme, the code is not mine and can be found here:
http://bryars.eu/projects/tv_grab_dvb/

**Comment by kanehekili** [comment]
The patched code can now be found in the build directory

**Comment by grkblood13** [comment]
If I run it an xml file with be generated with the channel ids but the programme data won't be captured. Not sure why that is exactly.

**Comment by kanehekili** [comment]
I'd start with czap first. It needs the xml file in proper syntax in the ~/.czap folder, called channels.conf
Each line has to look like this:
arte HD:418000000:INVERSION_AUTO:6900000:FEC_NONE:QAM_256:6661:6662:11120
It is important to create that file in this manner, so it can be read by czap. 
Using w-scan worked best for me. May I ask, what kind of "tuner" you have?
I've tested the code with a dvb-t and a dvb-c usb device. 
This procedure is described in the readme with all necessary settings. 
How to test: (works only with a cable tuner, else you will need the tzap command for dvb-t)
czap -l
...
 40 rbb Berlin:458000000:INVERSION_AUTO:6900000:FEC_NONE:QAM_256:601:602:28206
 41 NDR MV:458000000:INVERSION_AUTO:6900000:FEC_NONE:QAM_256:2401:2402:28224
 42 MDR Th:458000000:INVERSION_AUTO:6900000:FEC_NONE:QAM_256:3001:3002:28230
...
then try it : czap -n 40
you will get information about the channel...
status 1f | signal ffee | snr ffee | ber 00000000 | unc 00000000 | FE_HAS_LOCK
status 1f | signal ffee | snr ffee | ber 00000000 | unc 00000000 | FE_HAS_LOCK

Important are "signal" and "snr". How do they look?
